name: Python

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.8', '3.12' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starlette fastapi pytest pytest-cov
    - name: Test with coverage
      if: ${{ matrix.python-version == '3.12' }}
      run: pytest --cov --cov-config=.coveragerc tests
    - name: Upload code coverage report
      if: ${{ matrix.python-version == '3.12' }}
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    - name: Test without coverage
      if: ${{ matrix.python-version != '3.12' }}
      run: pytest tests

  test-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.8', '3.12' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starlette fastapi pytest
    - name: Test without coverage
      run: pytest tests

  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.8', '3.12' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starlette fastapi pytest
    - name: Test without coverage
      run: pytest tests
